### ISSUE TITLE
How to deal with recursive schemas?

### ISSUE THREAD

**Issue by diya-dhan** [hashicorp/terraform-plugin-framework#922] opened 2024-02-14 22:46 UTC
### Module version

```
v1.5.0
```

### Relevant provider source code

```go
var folderSchemaAttributes = map[string]schema.Attribute{
	"created_by": schema.StringAttribute{
		MarkdownDescription: "The details of the user that created the folder.",
	},
	"created_date": schema.StringAttribute{
		MarkdownDescription: "The date and time when the folder was created in.",
		Computed:            true,
	},
	"folders": schema.ListNestedAttribute{
		NestedObject: schema.NestedAttributeObject{
			Attributes: folderSchemaAttributes,
		},
		MarkdownDescription: "The list of folders contained in this folder",
	},
}


```

### Expected Behavior
I am trying to create a map of schema attributes where one of the attribute's references itself. w.r.t to the above example, a folder can contain a list of folders within itself, and folders all have the same set of attributes (For the sake of simplicity I have removed  most of the other attributes). 

Since the folders can be represented with the same set attributes, I would like to reference it in a recursive manner.

### Actual Behavior
I was faced with the following error:
```initialization cycle: folderSchemaAttributes refers to itself``` compiler [InvalidInitCycle](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#InvalidInitCycle)

Essentially, I am unable to achieve this recursive referencing.

**Comment by bendbennett** [comment] 2024-02-15 07:44
Hi @diya-dhan :wave,

Sorry you ran into trouble here.

Using the code that you have supplied I see a compiler error, indicating ` undefined: folderSchemaAttributes`.
An equivalent example on the [Go Playground](https://go.dev/play/p/w5JAX2lr7JF) illustrates the same issue.
Even if this were possible I believe that this would lead to infinite recursion. 

The question of how to [handle recursive schemas](https://discuss.hashicorp.com/t/recurisve-schema-using-terraform-plugin-framework/46952) has previously been raised on [Discuss](https://discuss.hashicorp.com/). Briefly, the schema system within Terraform does not directly support recursive schemas, but a couple of alternatives are described in the [response on Discuss](https://discuss.hashicorp.com/t/recurisve-schema-using-terraform-plugin-framework/46952/2?u=bendbennett). 

As it seems that this is not a bug with the Framework itself, I'm going to close this issue, but please feel free to direct questions regarding schema structure to the [Terraform Providers](https://discuss.hashicorp.com/c/terraform-providers/31) section of Discuss.

**Closed by bendbennett** 2024-02-15 07:44 UTC
Labels: bug
