### ISSUE TITLE
Error in `PlanResourceChange` for null `SingleNestedAttributes`

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-plugin-framework#174] opened 2021-09-21 15:35 UTC
### Module version

`main` at commit 8de1d13d86360d40e0a8b5f881a1b4bd7b3c607a.

I have an `Attribute` defined in `Schema` as

```go
		"retention_properties": {
			Description: "The retention duration of the memory store and the magnetic store.",
			Attributes: tfsdk.SingleNestedAttributes(
				map[string]tfsdk.Attribute{
					"magnetic_store_retention_period_in_days": {
						Description: "The duration for which data must be stored in the magnetic store.",
						Type:        types.StringType,
						Optional:    true,
					},
					"memory_store_retention_period_in_hours": {
						Description: "The duration for which data must be stored in the memory store.",
						Type:        types.StringType,
						Optional:    true,
					},
				},
			),
			Optional: true,
		},
```

In `Config` I have:

```terraform
resource "abc_def" "test" {
  retention_properties = {
    magnetic_store_retention_period_in_days = 90
    memory_store_retention_period_in_hours  = 24
  }
}
```

Refreshing the resource from the cloud provider returns:

```
Response.State.Raw: value="tftypes.Object["id":tftypes.String, "retention_properties":tftypes.Object["magnetic_store_retention_period_in_days":tftypes.String, "memory_store_retention_period_in_hours":tftypes.String]]
<"id":tftypes.String<"ewbankkit-test|ewbankkit-test">,"retention_properties":tftypes.Object["magnetic_store_retention_period_in_days":tftypes.String, "memory_store_retention_period_in_hours":tftypes.String]<null>>
```

i.e. no `retention_properties`.

Terraform correctly reports

```
      - .retention_properties: was cty.ObjectVal(map[string]cty.Value{"magnetic_store_retention_period_in_days":cty.StringVal("90"), "memory_store_retention_period_in_hours":cty.StringVal("24")}), but now null
```

but when Terraform calls `PlanResourceChange` the framework reports errors:

```
╷
│ Error: State Read Error
│ 
│   with abc_def.test,
│   on main.tf line 28, in resource "abc_def" "test":
│   28: resource "abc_def" "test" {
│ 
│ An unexpected error was encountered trying to read an attribute from the state. This is always an error in the provider. Please report the following to the
│ provider developer:
│ 
│ AttributeName("magnetic_store_retention_period_in_days") still remains in the path: step cannot be applied to this value
╵
╷
│ Error: State Read Error
│ 
│   with abc_def.test,
│   on main.tf line 28, in resource "abc_def" "test":
│   28: resource "abc_def" "test" {
│ 
│ An unexpected error was encountered trying to read an attribute from the state. This is always an error in the provider. Please report the following to the
│ provider developer:
│ 
│ AttributeName("memory_store_retention_period_in_hours") still remains in the path: step cannot be applied to this value
╵
```

**Comment by paddycarver** [comment] 2021-09-21 15:41
From my look at this, I believe this is a duplicate of #150.

**Closed** 2021-09-21 15:42 UTC
Labels: bug
