### ISSUE TITLE
implement helper/logging/NewLoggingHTTPTransport  as SDKv2

### ISSUE THREAD

**Issue by azrdev** [hashicorp/terraform-plugin-framework#976] opened 2024-04-10 11:40 UTC
### Module version

current framework v1.7.0

### Use-cases

Logging all backend API communications for debugging (esp. during provider development) should be simple.

### Attempted Solutions

one can write a request/response logger manually, but it's some dozens of sloc for a common purpose

### Proposal

Implement a ready-to-use "log all requests" component, like SDKv2 provides: https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/logging#NewLoggingHTTPTransport

**Comment by bflad** [comment] 2024-04-10 11:57
Drive-by comment: https://github.com/hashicorp/terraform-plugin-log/issues/91 is a related feature request for whomever triages this.

**Comment by bendbennett** [comment] 2024-04-11 09:01
Hi @azrdev 👋 

Thank you for raising this issue.

This appears to be a duplicate of [Consider tflog http.Transport Implementation](https://github.com/hashicorp/terraform-plugin-log/issues/91#top), so I'm going to close this issue. 

Please feel free to upvote [Consider tflog http.Transport Implementation](https://github.com/hashicorp/terraform-plugin-log/issues/91#top) and we'll evaluate moving forwards with that issue on the basis of the level of community interest. Thanks.

**Closed by bendbennett** 2024-04-11 09:01 UTC
Labels: enhancement
