### ISSUE TITLE
Value Conversion Error for timeouts attribute

### ISSUE THREAD

**Issue by aorith** [hashicorp/terraform-plugin-framework#793] opened 2023-07-06 07:41 UTC
### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.3.2
```
### Relevant provider source code

```go
func (r *siteResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description:         "Manages company sites (domains)",
		MarkdownDescription: "Manages company sites (domains)",

		Attributes: map[string]schema.Attribute{
			"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
				Create: true,
			}),

```

```go
type Site struct {
	Timeouts timeouts.Value `tfsdk:"timeouts"`
	ID       types.Int64    `tfsdk:"id"`
	Domain   types.String   `tfsdk:"domain"`
	Active   types.Bool     `tfsdk:"active"`
}
```

### Terraform Configuration Files

```hcl
resource "transparentedge_site" "all" {
  for_each = var.sites
  domain   = each.key
  timeouts = {
    create = "120s"
  }
}
```
### Debug Output

```
│ Expected type: types.ObjectType["create":basetypes.StringType]
│ Value type: types.ObjectType["create":basetypes.StringType]
│ Path: timeouts
╵
╷
│ Error: Value Conversion Error
│
│   with transparentedge_site.all["demo.transparentedge.eu"],
│   on main.tf line 38, in resource "transparentedge_site" "all":
│   38:   timeouts = {
│   39:     create = "120s"
│   40:   }
```

### Expected Behavior

The type is correct, it should not complain.

### Actual Behavior

Value conversion error

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

- https://github.com/hashicorp/terraform-provider-aws/issues/32322

**Comment by bflad** [comment] 2023-07-06 20:40
Thank you for reporting this, @aorith, and sorry you are running into trouble here. The code snippets provided _seem_ correct at first glance, but we will take a deeper look.

**Comment by bflad** [comment] 2023-07-06 20:41
By the way, what version of terraform-plugin-framework-timeouts are you using?

**Comment by aorith** [comment] 2023-07-07 07:04
> By the way, what version of terraform-plugin-framework-timeouts are you using?

`v0.4.0`

I was updating from:

```
github.com/hashicorp/terraform-plugin-framework v1.2.0
github.com/hashicorp/terraform-plugin-framework-timeouts v0.3.1
```

It also fails with `github.com/hashicorp/terraform-plugin-framework v1.3.1`.

**Comment by bflad** [comment] 2023-07-07 13:23
The fix for this issue, which was caused by more correct value checking in terraform-plugin-framework v1.3.0 and later, has been released with [terraform-plugin-framework-timeouts v0.4.1](https://github.com/hashicorp/terraform-plugin-framework-timeouts/releases/tag/v0.4.1). Please reach out if you have any further issues, and thank you again for reporting this.

**Closed by bflad** 2023-07-07 13:23 UTC
Labels: bug
