### ISSUE TITLE
Error updating from nil (known) to an interpolated value (unknown)

### ISSUE THREAD

**Issue by appilon** [hashicorp/terraform-plugin-framework#210] opened 2021-10-26 02:34 UTC
### Module version

```
0.4.2
```

### Terraform Configuration Files

apply
```hcl
resource "sample_resource" "test" {
  name           = "test"
 # parent_id = resource.sample_resource.parent.id
}
```
then apply
```hcl
resource "sample_resource" "parent" {
  name           = "parent"
}

resource "sample_resource" "test" {
  name           = "child"
  parent_id = resource.sample_resource.parent.id
}
```

### Expected Behavior

Should apply correctly
### Actual Behavior

```
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/hashicorp/sample" planned an invalid value for sample_sample.test.parent_id: planned value cty.NullVal(cty.String) does not match config value
│ cty.UnknownVal(cty.String).
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
### Steps to Reproduce

Apply the configs

**Comment by bflad** [comment] 2021-11-01 13:44
Hey @appilon 👋  Thanks for raising this and sorry you ran into trouble here. Can you provide the full schema for the `parent_id` attribute?

**Comment by appilon** [comment] 2021-11-01 15:54
Of course
```
"parent_id": {
				Description: "The ID of the parent role.",
				Type:        types.StringType,
				Optional:    true,
				PlanModifiers: tfsdk.AttributePlanModifiers{
					NormalizeId{},
				},
			},
```
I don't think the presence of the planmodifer affects anything but for reference
```
func (NormalizeId) Modify(_ context.Context, req tfsdk.ModifyAttributePlanRequest, resp *tfsdk.ModifyAttributePlanResponse) {
	if req.AttributeState == nil {
		return
	}
	plan := req.AttributePlan.(types.String)
	state := req.AttributeState.(types.String)
	if normalizeId(plan.Value) == normalizeId(state.Value) {
		resp.AttributePlan = state
	} else {
		resp.AttributePlan = plan
	}
}
```

**Comment by paddycarver** [comment] 2021-12-15 09:26
Hey @appilon, @hashicorp/terraform-core is saying that there shouldn't be a situation in which the config is unknown and the plan is null. My understanding is if the config has an unknown value, the planned value should default to unknown, as well.

1. Are you modifying the plan at all?
2. Do you happen to have a consistent reproduction of this? I think some framework or plugin-go logging could shed a lot of light on where this problem is coming up very quickly if we have a repro.
3. What Terraform version do you run into this with?

**Comment by bflad** [comment] 2022-03-16 17:57
Hey again @appilon 👋  Is this still an issue? If so, can you please answer the above? Thanks so much!

**Comment by appilon** [comment] 2022-03-16 22:09
@bflad I would have to refresh my memory around it with the Salesforce provider, I will try and prioritize that this week.

**Comment by bflad** [comment] 2022-07-06 15:36
Closing since it has been awhile without any further information. Please feel free to reopen, if desired.

I have a sneaking suspicion that core might have wanted `Computed: true` on the attribute so it knows that the value could come from the provider, rather than just the configuration. #31 may be related, if we adjust the framework to always mark attributes as Computed when Optional.

**Closed by bflad** 2022-07-06 15:36 UTC
Labels: bug
