### ISSUE TITLE
Plan modifiers inside nested attributes doesn't seem to do anything in SingleNestedAttribute

### ISSUE THREAD

**Issue by pksunkara** [hashicorp/terraform-plugin-framework#489] opened 2022-09-15 22:57 UTC
### Module version

```
github.com/hashicorp/terraform-plugin-framework v0.11.1
```

### Relevant provider source code

```go
func (t teamResourceType) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		MarkdownDescription: "Test team.",
		Attributes: map[string]tfsdk.Attribute{
			"bool_known_default": {
				MarkdownDescription: "Boolean with known default. **Default** `true`.",
				Type:                types.BoolType,
				Optional:            true,
				Computed:            true,
				PlanModifiers: tfsdk.AttributePlanModifiers{
					modifiers.DefaultBool(true),
				},
			},
			"nullable_bool": {
				MarkdownDescription: "Nullable boolean. **Default** `null`.",
				Type:                types.BoolType,
				Optional:            true,
				Computed:            true,
				PlanModifiers: tfsdk.AttributePlanModifiers{
					modifiers.NullableBool(),
				},
			},
			"nested": {
				MarkdownDescription: "Nested block.",
				Optional:            true,
				Computed:            true,
				// PlanModifiers: tfsdk.AttributePlanModifiers{
				//	defaultObjectModifier{},
				// },
				Attributes: tfsdk.SingleNestedAttributes(map[string]tfsdk.Attribute{
					"bool_empty_default": {
						MarkdownDescription: "Bool with empty default. **Default** `false`.",
						Type:                types.BoolType,
						Optional:            true,
						Computed:            true,
						PlanModifiers: tfsdk.AttributePlanModifiers{
							modifiers.DefaultBool(false),
						},
					},
				}),
			},
		},
	}, nil
}

type teamResourceData struct {
	BoolKnownDefault            types.Bool    `tfsdk:"bool_known_default"`
	NullableBool                types.Bool    `tfsdk:"nullable_bool"`
	Nested                      types.Object  `tfsdk:"nested"`
}

func (r teamResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data teamResourceData

	diags := req.Plan.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	input := TeamsInsertInput{
		BoolKnownDefault:   data.BoolKnownDefault.Value,
	}

	if !data.NullableBool.IsNull() {
		input.NullableBool = &data.NullableBool.Value
	}

	tflog.Warn(ctx, fmt.Sprintf("%v", data.Nested))

	input.NestedBoolEmptyDefault = data.Nested.Attrs["bool_empty_default"].(types.Bool).Value

	response, err := createTeam(context.Background(), r.provider.client, input)

	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create team, got error: %s", err))
		return
	}

	tflog.Trace(ctx, "created a team")

	team := response.InsertIntoTeamsCollection.Records[0]

	data.BoolKnownDefault = types.Bool{Value: team.BoolKnownDefault}

	if team.NullableBool != nil {
		data.NullableBool = types.Bool{Value: *team.NullableBool}
	}

	data.Nested = types.Object{
		AttrTypes: map[string]attr.Type{
			"bool_empty_default": types.BoolType,
		},
		Attrs: map[string]attr.Value{
			"bool_empty_default": types.Bool{Value: team.NestedBoolEmptyDefault},
		},
	}

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}
```

The modifiers are defined [here](https://github.com/terraform-community-providers/terraform-plugin-framework-utils/blob/master/modifiers/default_bool.go)

### Terraform Configuration Files

```hcl
resource "test_team" "default" {}
```

### Context

I created some plan modifiers that I can use in my providers to imitate the default value on the API service for the provider. If an object's attribute is by default `true` in the API service, I use the modifier `DefaultBool(true)` and that sets the value during creation of this resource in the plan correctly as `true`. I did similar stuff for nullable values.

Now, I wanna use single nested attributes and have a key for it called `nested` which contains some attributes that also have defaults.

### Actual Behavior

Adding the modifiers to these nested attributes doesn't seem to work at all. I am getting the attribute value as unknown in plan for the whole nested object which in turn errors out when trying to create a request body for the API service.

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # test_team.default will be created
  + resource "test_team" "default" {
      + bool_known_default             = true
      + nested                         = {
          + bool_empty_default = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

test_team.default: Creating...
2022-09-15T23:42:41.684+0100 [WARN]  provider.terraform-provider-test_v1.0.0: <unknown>: @caller=/home/pksunkara/Coding/terraform-community-providers/terraform-plugin-framework-utils/test/terraform-provider-test/internal/provider/resource_team.go:375 tf_req_id=7ca25bcb-a913-5086-d506-fc7bada1bce0 @module=test tf_provider_addr=registry.terraform.io/terraform-community-providers/test tf_resource_type=test_team tf_rpc=ApplyResourceChange timestamp=2022-09-15T23:42:41.684+0100
2022-09-15T23:42:41.687+0100 [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
2022-09-15T23:42:41.688+0100 [ERROR] vertex "test_team.default" error: Plugin did not respond
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-test_v1.0.0 plugin:

panic: interface conversion: attr.Value is nil, not types.Bool

goroutine 82 [running]:
terraform-provider-test/internal/provider.teamResource.Create({{{_, _}, _, {_, _}}}, {_, _}, {{{{0xc3fe30, 0xc000457b30}, {0xa6a0a0, ...}}, ...}, ...}, ...)
	/home/pksunkara/Coding/terraform-community-providers/terraform-plugin-framework-utils/test/terraform-provider-test/internal/provider/resource_team.go:377 +0xb1d
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc00022d180, {0xc3d0b0, 0xc000456d20}, 0xc0001b5408, 0xc0001b53a8)
	/home/pksunkara/.go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.11.1/internal/fwserver/server_createresource.go:90 +0x836
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc3d0b0?, {0xc3d0b0, 0xc000456d20}, 0xc00021d900, 0xc0001b5578)
	/home/pksunkara/.go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.11.1/internal/fwserver/server_applyresourcechange.go:54 +0x4a8
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc00022d180, {0xc3d0b0?, 0xc000456bd0?}, 0xc00021d8b0)
	/home/pksunkara/.go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.11.1/internal/proto6server/server_applyresourcechange.go:52 +0x27b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc000227180, {0xc3d0b0?, 0xc0004563f0?}, 0xc00014e620)
	/home/pksunkara/.go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov6/tf6server/server.go:816 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xb0d700?, 0xc000227180}, {0xc3d0b0, 0xc0004563f0}, 0xc00014e5b0, 0x0)
	/home/pksunkara/.go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002b81e0, {0xc3ff90, 0xc0002a56c0}, 0xc0003eaa20, 0xc00028c2a0, 0x1065d60, 0x0)
	/home/pksunkara/.go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0002b81e0, {0xc3ff90, 0xc0002a56c0}, 0xc0003eaa20, 0x0)
	/home/pksunkara/.go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/pksunkara/.go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/pksunkara/.go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-test_v1.0.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

Adding the modifiers to these nested attributes should work and the plan should show me the value for the attribute as the same one as I set in these modifiers.

### Solutions discarded

1. I could check for unknown values during the building of request and correctly handle it instead of asserting the type and crashing. But this is not the correct way because we would want to show the value of the attribute in the plan.
2. I could make a plan modifier for the nested block that returns a `type.Object` with the defaults we want for the attributes inside it, but there are two issues with this:
  * We would need to build a custom plan modifier for every nested block because the attributes will change.
  * There's no more meaning to the individual attribute's plan modifiers anymore.

---

@bflad I would really really appreciate some help in pointing out the right way to do this. I have spent the last 2 weeks banging my head on how to get nested attributes working and finally figured out that I need to use `types.Object` but now ran into this problem.

**Comment by bflad** [comment] 2022-09-20 18:47
Hi @pksunkara 👋 Does it work any differently or better with version 0.13.0 by chance? There have been changes to the plan modification logic since version 0.11.1. If upgrading still has unexpected behaviors, we can dive into this further.

**Comment by bflad** [comment] 2022-09-22 21:06
I spent some time working on this today and this behavior may be unfortunately necessary by default to prevent Terraform `provider produced inconsistent results after apply` errors. There is however a generic plan modifier you can implement to achieve the behavior you want.

The trick here is that when `nested` (an object containing attributes) is not defined in the configuration, it is null. Because the attribute is marked as `Computed`, the framework will automatically mark the object as unknown in the plan to prevent errors if the provider actually filled in a value for it during apply. The object being marked as unknown in the plan prevents children attribute plan modifiers from automatically executing, since it is not valid for the object to be unknown, but also have children attributes with known attribute plan values.

To modify the plan where the children attribute plan modifiers are automatically run, the object can be marked as known and all children attributes marked as unknown via a plan modifier at that level, e.g.

```go
func RunObjectAttributePlanModifiersOnUnknown() tfsdk.AttributePlanModifier {
	return runObjectAttributePlanModifiersOnUnknown{}
}

type runObjectAttributePlanModifiersOnUnknown struct{}

func (m runObjectAttributePlanModifiersOnUnknown) Description(ctx context.Context) string {
	return ""
}

func (m runObjectAttributePlanModifiersOnUnknown) MarkdownDescription(ctx context.Context) string {
	return ""
}

func (m runObjectAttributePlanModifiersOnUnknown) Modify(ctx context.Context, req tfsdk.ModifyAttributePlanRequest, resp *tfsdk.ModifyAttributePlanResponse) {
	if !req.AttributePlan.IsUnknown() {
		return
	}

	var object types.Object

	resp.Diagnostics.Append(tfsdk.ValueAs(ctx, req.AttributePlan, &object)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Unknown objects will not have Attrs, which will cause an error.
	if object.Attrs == nil {
		object.Attrs = make(map[string]attr.Value, len(object.AttrTypes))
	}

	for name, attrType := range object.AttrTypes {
		attrValue, err := attrType.ValueFromTerraform(ctx, tftypes.NewValue(attrType.TerraformType(ctx), tftypes.UnknownValue))

		if err != nil {
			resp.Diagnostics.AddAttributeError(
				req.AttributePath.AtName(name),
				"Attribute Plan Modification Error",
				"While creating unknown values for object attributes, an unexpected error occurred. Please report the following to the provider developers.\n\n"+
					"Error: "+err.Error(),
			)
		}

		object.Attrs[name] = attrValue
	}

	object.Unknown = false

	resp.AttributePlan = object
}
```

```go
			"nested": {
				MarkdownDescription: "Nested block.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: tfsdk.AttributePlanModifiers{
					RunObjectAttributePlanModifiersOnUnknown(),
				},
				Attributes: tfsdk.SingleNestedAttributes(map[string]tfsdk.Attribute{
					"bool_empty_default": {
						MarkdownDescription: "Bool with empty default. **Default** `false`.",
						Type:                types.BoolType,
						Optional:            true,
						Computed:            true,
						PlanModifiers: tfsdk.AttributePlanModifiers{
							DefaultBool(false),
						},
					},
				}),
			},
```

The children attribute plan modifiers are then called and it will cause a plan in this case of:

```
  |   + resource "framework_team" "test" {
  |       + id     = (known after apply)
  |       + nested = {
  |           + bool_empty_default = false
  |         }
  |     }
```

There could be other unexpected behaviors with a more complex schema under the object, but hope this helps get you started for this specific use case. I'm not sure how _generally_ useful this particular attribute plan modifier would be for other provider developers, so I'm hesitant to say it's something we should include by default in the framework unless there are other similar requests.

**Closed by bflad** 2022-09-22 21:06 UTC
Labels: bug

**Comment by pksunkara** [comment] 2022-09-24 11:31
@bflad Thanks, that worked. I added that modifier to my [utils](https://github.com/terraform-community-providers/terraform-plugin-framework-utils#unknownattributesonunknown) library in case anyone wants to use it.

While I have you here, I am wondering if I can improve the ergonomics of using `types.Object`. Let's say I want to use a struct so that code is better maintainable.

```go
type nested struct {
	BoolEmptyDefault types.Bool `tfsdk:"bool_empty_default"`
}
```

##### Reading from Object

Previous code

```go
	input.NestedBoolEmptyDefault = data.Nested.Attrs["bool_empty_default"].(types.Bool).Value
```

I improved it to

```go
	diags = data.Nested.As(ctx, &nestedData, types.ObjectAsOptions{})
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	input.NestedBoolEmptyDefault = nestedData.BoolEmptyDefault.Value
```

##### Writing to Object

```go
	data.Nested = types.Object{
		AttrTypes: map[string]attr.Type{
			"bool_empty_default": types.BoolType,
		},
		Attrs: map[string]attr.Value{
			"bool_empty_default": types.Bool{Value: team.NestedBoolEmptyDefault},
		},
	}
```

I have no idea on how to improve it. How do I convert my `nested` struct to `Object`?

---

And I am also wondering why this is not the default behaviour? That way I can use my `nested` struct directly in `teamResourceData` instead of having to use an intermediary `types.Object`
