### ISSUE TITLE
Support per-resource, per-operation timeouts

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-plugin-framework#68] opened 2021-07-14 20:56 UTC
### Module version

```console
% go list -m github.com/hashicorp/terraform-plugin-framework/...
github.com/hashicorp/terraform-plugin-framework v0.1.0
```

It will be necessary to support [per-resource, per-operation timeouts](https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts).

**Comment by paddycarver** [comment] 2021-07-17 20:43
Possibly a duplicate of #62.

**Comment by ewbankkit** [comment] 2021-07-22 14:57
Yes it is - I thought that the underlying Terraform protocol had special knowledge of the `timeouts` block but it seems that this is provider-side functionality.

**Closed** 2021-07-22 14:57 UTC
Labels: enhancement
