### ISSUE TITLE
Nil config throws error on validate

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-framework#105] opened 2021-08-17 07:01 UTC
Bug on `main` (abe64d6).

If the config is nil, the framework throws an error on validate.

For example, consider the following test case:

```go
		"no_config": {
			config:       tftypes.NewValue(testServeProviderProviderType, nil),
			provider:     &testServeProvider{},
			providerType: testServeProviderProviderType,
                },
```
This leads to the following error:

```go
--- FAIL: TestServerValidateProviderConfig (0.00s)
    --- FAIL: TestServerValidateProviderConfig/config_validators_nil_config (0.00s)
        serve_test.go:653: Unexpected diff in diagnostics (+wanted, -got):   []*tfprotov6.Diagnostic(
            - 	{
            - 		&{
            - 			Severity:  s"ERROR",
            - 			Summary:   "Configuration Read Error",
            - 			Detail:    "An unexpected error was encountered trying to read an attribute "...,
            - 			Attribute: s`AttributeName("string")`,
            - 		},
            - 	},
            + 	nil,
              )
```

The error is due to #106.

However, once #106 is fixed, an error is still thrown, this time by this line: https://github.com/hashicorp/terraform-plugin-framework/blob/abe64d602ac541e9aa398b10b4b619ccba023686/tfsdk/attribute.go#L259 This is because, unlike `PlanResourceChange`, the handlers for `ValidateResourceConfig` and similar do not exit early when config (plan, in the PlanResourceChange case) is nil.

**Comment by paddycarver** [comment] 2021-08-18 11:05
Do we have any intuition on when a null config would be present? In my mental model, we'll always get a non-null object, though all its values may be null.

**Comment by apparentlymart** [comment] 2021-09-08 18:44
I share the intuition that it seems weird for a null object to appear as the representation of the configuration during `ValidateResourceConfig`. That would represent to me the `resource` block not being present at all, but in that case I wouldn't expect Terraform Core to call `ValidateResourceConfig`, and instead it would go on to just synthesize a "delete" plan locally. (we don't currently ask the provider for any contributions to a delete plan.)

With that said, our introduction of attributes that can have nested structural types (that is, block-like capabilities but using the attribute syntax) _does_ introduce some new opportunities for nulls to appear at lower levels of the data structure. With block syntax Terraform guarantees that the attribute (`cty`-meaning) representing a block type will never be null or unknown -- an assumption the old SDK depended on -- but with the new schema feature there is no such guarantee, and so either the framework or the provider code must deal with null values in that context. I mention that only for completeness; it's not clear to me whether this issue is specifically about the top-level object representing the whole configuration, or if it could also apply to nested objects.

**Comment by paddycarver** [comment] 2021-09-15 11:08
I think my hot take is this is "working as intended" and that a null config is something we should never encounter. @bflad, @kmoe do either of you want to champion "null config is a reasonable thing to encounter and we should account for it", or do we want to close this out?

**Comment by paddycarver** [comment] 2021-09-16 16:41
Let's close this out, and if someone wants to champion it as something that can happen outside our unit tests, we can open a new issue or reopen this issue.

**Closed by paddycarver** 2021-09-16 16:41 UTC
Labels: bug
